#Test setup-jf-cli-install
name: 51-test-setup-jf-cli

on: workflow_dispatch #on

jobs:
  echo-release-version:
    runs-on: ubuntu-latest
    steps:
      - name: release version
        run: uname -a
      - name: amount of memory
        run: free -m
  install-jf:
    runs-on: ubuntu-latest
    steps:
      - name: install jf
        uses: jfrog/setup-jfrog-cli@v4
# + Authentication method
      - name: check jf version
        run: jf --version
            